spring.application.name=BloxBlueprint
spring.datasource.url=jdbc:postgresql://localhost:5433/blox_blueprint
spring.datasource.username=postgres
spring.datasource.password=MyPassword!
spring.jpa.hibernate.ddl-auto=update
jwt.secret=replace-this-with-a-long-random-secret-key
jwt.expiration=3600000